//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cv
    {
        public Cv()
        {
            this.CompetenceGenerales = new HashSet<CompetenceGenerale>();
            this.Formations = new HashSet<Formation>();
            this.Missions = new HashSet<Mission>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Titre { get; set; }
    
        public virtual ICollection<CompetenceGenerale> CompetenceGenerales { get; set; }
        public virtual ICollection<Formation> Formations { get; set; }
        public virtual ICollection<Mission> Missions { get; set; }
    }
}
