//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        public int Id { get; set; }
        public string Poste { get; set; }
        public string LibelleMission { get; set; }
        public string Description { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public int CvId { get; set; }
        public int ClientId { get; set; }
        public int SSIIId { get; set; }
    
        public virtual Cv Cv { get; set; }
        public virtual Client Client { get; set; }
        public virtual SSII SSII { get; set; }
    }
}
